package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Autotests Cloud")
    void generatedTest() {
        step("open https://sport.business-gazeta.ru/", () -> {
            // todo
        });

        step("step1", () -> {
            // todo
        });

        step("step2", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://sport.business-gazeta.ru/'", () ->
            open("https://sport.business-gazeta.ru/"));

        step("Page title should have text 'Спорт, Казань, Уфа, хоккей, футбол, волейбол, новости спорта, аналитика, разбор матчей на БИЗНЕС Online | Спорт на БИЗНЕС Online'", () -> {
            String expectedTitle = "Спорт, Казань, Уфа, хоккей, футбол, волейбол, новости спорта, аналитика, разбор матчей на БИЗНЕС Online | Спорт на БИЗНЕС Online";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://sport.business-gazeta.ru/'", () ->
            open("https://sport.business-gazeta.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}